# Header
menu:
  首页: /
  关于: /about
  存档: /archives
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- logo
- info
- category
- tagcloud
- recent_posts
- blogroll


# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

baidu_tongji: true